### ISSUE TITLE
Being clear in the readme about what Alt+J doesn't do but is expected from a plugin called multicursor

### ISSUE THREAD

**Issue by z--aszlo** [caspark/eclipse-multicursor#24]
Reading the description of this plugin made me believe that with this plugin finally I can place multiple instances of cursor to any place in the editor. Like having many rows  of constructor variable definitions and want to place a '?' in front of every variable that are not aligned into a column to use the alt+shift+a.

Now I don't really get it what the Alt+J does, neither am I so interested but it doesn't do what I expected from it. Maybe there are others with this same expectation and making a note on this could spare them precious minutes. Or provide the settings to achieve this functionality more clearly / with emphasis.

**Comment by caspark** [comment]
Thank you for the feedback.

The behaviour you describe was what I intended to implement, but I changed jobs & as a result stopped using Eclipse entirely before I got more than some bits and pieces of it working.

Specifically to manage expectations and save people time, I had already written the following under the first heading in the readme:

> This is implemented using Eclipse linked mode editing (similar to existing "rename in file" functionality), so *you can't go outside the initial edit area.*

I appreciate that not every potential plugin user knows what Eclipse linked mode editing is (a feature you only notice if you dig around the preferences menu), but I thought the italicised text was fairly clear. Were you still misled despite reading this text? Any suggestions for what I should write instead? Otherwise I'll just close this issue.

**Comment by z--aszlo** [comment]
Thanks for your reply.

Well, stating what you've just said would make it clearer:
"I intended to implement the multicursor behaviour by this plugin, but between stopped using Eclipse entirely before I got more than some bits and pieces of it working. So the project didn't achieve it's goal and what it can do is just similar to the existing "rename in file" functionality or linked mode editing, it doesn't go outside the initial edit area."

**Comment by caspark** [comment]
Thanks; readme updating & closing this issue.
